server {
    listen 80;
    listen [::]:80;
    server_name www.${DOMAIN};

    include /etc/nginx/includes/http-support.inc;

    location / {
        return 301 http://${DOMAIN}$request_uri;
    }
}

server {
    listen 80;
    listen [::]:80;
    server_name ${DOMAIN} localhost;

    include /etc/nginx/includes/http-support.inc;
    include /etc/nginx/includes/app.inc;
}
